name: CI2

on:
  push:
    branches: [main]
  pull_request:

jobs:
  list-tests:
    name: List tests
    runs-on: ubuntu-latest

    outputs:
      tests: ${{ steps.tests.outputs.tests }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Nix
        uses: cachix/install-nix-action@3715ab1a11cac9e991980d7b4a28d80c7ebdd8f9 # v27
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Set up magic Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@87b14cf437d03d37989d87f0fa5ce4f5dc1a330b # v8

      - name: Prepare Nix shell
        run: nix develop --impure .#ci

      - name: List tests
        id: tests
        run: echo "tests=$(nix develop --impure .#ci -c bash -c 'just list-with-tests | just as-json')" >> $GITHUB_OUTPUT

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: list-tests
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJson(needs.list-tests.outputs.tests) }}

    steps:
      - uses: dkershner6/switch-case-action@v1
        id: constructor-args
        with:
          default: ""
          conditionals-with-values: |
            ${{ matrix.module == 'gh' }} => --github-token env:GITHUB_TOKEN

      - name: Run pipeline
        uses: dagger/dagger-for-github@2f17ffec279ab28121a7030db49c2ab32378de2e # v7.0.2
        with:
          verb: call
          module: github.com/${{ github.repository }}/${{ matrix.module }}/tests@${{ github.ref }}
          args: ${{ steps.constructor-args.outputs.value }} all
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: "0.13.1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
