name: CI2

on:
  push:
    branches: [main]
  pull_request:

jobs:
  list-tests:
    name: List tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - run: just list-with-tests
