name: Publish

on:
  push:
    branches: [main]
    # tags: ["**/v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module:
          - apko
          - arc
          - archivist
          - aws-cli
          - bats
          - borgo
          - checksum
          - gh
          - go
          - golangci-lint
          - helm
          - helm-docs
          - kafka
          - kustomize
          - openapi-changes
          - openssh-server
          - php
          - php-cs-fixer
          - phpstan
          - postgres
          - psql
          - python
          - quarto
          - registry
          - registry-config
          - slsa-verifier
          - spectral
          - ssh-keygen
          - stainless
          - trivy
          - xcaddy
          - xk6

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Publish module
        uses: dagger/dagger-for-github@2f17ffec279ab28121a7030db49c2ab32378de2e # v7.0.2
        with:
          module: ${{ matrix.module }}
          verb: publish
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: "0.13.1"
